# Generated by Django 3.2.6 on 2025-06-18 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrd', '0022_auto_20250618_1016'),
        ('absensi', '0007_alter_absensi_status_absensi'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=False)),
                ('model_path', models.CharField(max_length=255)),
                ('num_faces', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Log Training',
                'verbose_name_plural': 'Log Training',
            },
        ),
        migrations.CreateModel(
            name='FaceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_dataset', models.CharField(help_text='Path relatif ke folder dataset wajah', max_length=255)),
                ('waktu_terdaftar', models.DateTimeField(auto_now_add=True)),
                ('last_trained', models.DateTimeField(blank=True, help_text='Waktu terakhir data digunakan untuk training', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('id_karyawan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='face_data', to='hrd.karyawan')),
            ],
            options={
                'verbose_name': 'Data Wajah',
                'verbose_name_plural': 'Data Wajah',
            },
        ),
        migrations.CreateModel(
            name='AbsensiMagang',
            fields=[
                ('id_absensi', models.AutoField(primary_key=True, serialize=False)),
                ('tanggal', models.DateField(auto_now_add=True)),
                ('waktu', models.TimeField(auto_now_add=True)),
                ('lokasi', models.CharField(help_text='Koordinat lokasi saat absensi', max_length=255)),
                ('status', models.CharField(choices=[('Hadir', 'Hadir'), ('Terlambat', 'Terlambat'), ('Izin', 'Izin'), ('Sakit', 'Sakit')], default='Hadir', max_length=25)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='absensi/screenshots/%Y/%m/%d/')),
                ('confidence_level', models.FloatField(default=0.0, help_text='Tingkat kepercayaan pengenalan wajah (0-100)')),
                ('verified', models.BooleanField(default=False, help_text='Status verifikasi absensi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id_karyawan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrd.karyawan')),
            ],
            options={
                'verbose_name': 'Absensi Magang',
                'verbose_name_plural': 'Absensi Magang',
                'unique_together': {('id_karyawan', 'tanggal')},
            },
        ),
    ]
