# Generated by Django 3.2.6 on 2025-06-19 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absensi', '0008_absensimagang_facedata_traininglog'),
    ]

    operations = [
        migrations.AddField(
            model_name='absensimagang',
            name='alamat',
            field=models.CharField(blank=True, help_text='Nama lokasi atau alamat saat absensi', max_length=500, null=True),
        ),
    ]
