# Generated by Django 3.2.6 on 2025-06-19 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absensi', '0009_absensimagang_alamat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absensimagang',
            name='status',
            field=models.CharField(choices=[('Hadir', 'Hadir'), ('Terlambat', 'Terlambat'), ('Izin', 'Izin'), ('Sakit', 'Sakit'), ('Tepat Waktu', 'Tepat Waktu')], default='Hadir', max_length=25),
        ),
    ]
