# Generated by Django 3.2.6 on 2025-06-30 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('absensi', '0011_faceencoding'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrainingLog',
        ),
    ]
