# Generated by Django 3.2.6 on 2025-06-30 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absensi', '0012_delete_traininglog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='absensimagang',
            name='alamat',
        ),
        migrations.RemoveField(
            model_name='absensimagang',
            name='confidence_level',
        ),
        migrations.RemoveField(
            model_name='absensimagang',
            name='lokasi',
        ),
        migrations.RemoveField(
            model_name='absensimagang',
            name='screenshot',
        ),
        migrations.RemoveField(
            model_name='absensimagang',
            name='verified',
        ),
        migrations.RemoveField(
            model_name='absensimagang',
            name='waktu',
        ),
        migrations.AddField(
            model_name='absensimagang',
            name='alamat_masuk',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='absensimagang',
            name='alamat_pulang',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='absensimagang',
            name='jam_masuk',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='absensimagang',
            name='jam_pulang',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='absensimagang',
            name='lokasi_masuk',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='absensimagang',
            name='lokasi_pulang',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='absensimagang',
            name='screenshot_masuk',
            field=models.ImageField(blank=True, null=True, upload_to='absensi/screenshots/masuk/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='absensimagang',
            name='screenshot_pulang',
            field=models.ImageField(blank=True, null=True, upload_to='absensi/screenshots/pulang/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='absensimagang',
            name='tanggal',
            field=models.DateField(),
        ),
    ]
