# Generated by Django 3.2.6 on 2025-06-30 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absensi', '0013_auto_20250630_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absensimagang',
            name='tanggal',
            field=models.DateField(auto_now_add=True),
        ),
    ]
