# Generated by Django 3.2.6 on 2025-06-30 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absensi', '0014_alter_absensimagang_tanggal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absensimagang',
            name='tanggal',
            field=models.DateField(),
        ),
    ]
