# Generated by Django 3.2.6 on 2025-06-30 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absensi', '0015_alter_absensimagang_tanggal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absensimagang',
            name='status',
            field=models.CharField(choices=[('Tepat Waktu', 'Tepat Waktu'), ('Terlambat', 'Terlambat')], default='Tepat Waktu', max_length=25),
        ),
    ]
