# Generated by Django 3.2.6 on 2025-07-01 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absensi', '0016_alter_absensimagang_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='absensimagang',
            name='keterangan',
            field=models.CharField(choices=[('WFO', 'WFO'), ('WFH', 'WFH'), ('Izin Telat', 'Izin Telat'), ('Izin Sakit', 'Izin Sakit')], max_length=25, null=True),
        ),
    ]
