# Generated by Django 3.2.6 on 2026-01-21 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absensi', '0017_absensimagang_keterangan'),
    ]

    operations = [
        migrations.AddField(
            model_name='absensimagang',
            name='overtime_alert_sent',
            field=models.BooleanField(default=False, help_text='Flag untuk tracking apakah alert overtime sudah dikirim'),
        ),
        migrations.AddField(
            model_name='absensimagang',
            name='reminder_sent',
            field=models.BooleanField(default=False, help_text='Flag untuk tracking apakah reminder 10 AM sudah dikirim'),
        ),
        migrations.AddField(
            model_name='rules',
            name='batas_checkin_reminder',
            field=models.TimeField(default='10:00:00', help_text='Waktu untuk mengirim reminder check-in (default: 10:00)'),
        ),
        migrations.AddField(
            model_name='rules',
            name='batas_deadline_checkin',
            field=models.TimeField(default='11:00:00', help_text='Batas akhir check-in (default: 11:00)'),
        ),
        migrations.AddField(
            model_name='rules',
            name='batas_overtime',
            field=models.TimeField(default='18:30:00', help_text='Batas waktu untuk alert overtime (default: 18:30)'),
        ),
        migrations.AddField(
            model_name='rules',
            name='durasi_kerja_jam',
            field=models.DecimalField(decimal_places=1, default=8.5, help_text='Durasi kerja dalam jam (contoh: 8.5 untuk 8 jam 30 menit)', max_digits=3),
        ),
        migrations.AddField(
            model_name='rules',
            name='min_jam_masuk',
            field=models.TimeField(default='06:00:00', help_text='Waktu minimum check-in (default: 06:00)'),
        ),
    ]
