# Generated by Django 3.2.6 on 2025-12-30 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absensi', '0017_absensimagang_keterangan'),
    ]

    operations = [
        migrations.CreateModel(
            name='LokasiKantor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(help_text='Nama lokasi (contoh: ASEEC)', max_length=100, unique=True)),
                ('latitude', models.DecimalField(decimal_places=8, help_text='Koordinat lintang', max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, help_text='Koordinat bujur', max_digits=11)),
                ('radius', models.IntegerField(default=150, help_text='Radius toleransi dalam meter')),
                ('is_active', models.BooleanField(default=True, help_text='Apakah lokasi ini aktif digunakan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lokasi Kantor',
                'verbose_name_plural': 'Lokasi Kantor',
            },
        ),
    ]
