# Generated by Django 3.2.6 on 2026-01-21 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('absensi', '0018_auto_20260121_2059'),
        ('absensi', '0018_lokasikantor'),
    ]

    operations = [
    ]
