# Generated by Django 3.2.6 on 2026-01-21 15:21

import apps.absensi.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absensi', '0019_merge_0018_auto_20260121_2059_0018_lokasikantor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faceencoding',
            name='user',
        ),
        migrations.AddField(
            model_name='absensimagang',
            name='aktivitas_wfh',
            field=models.TextField(blank=True, help_text='Deskripsi aktivitas yang dikerjakan saat WFA', null=True),
        ),
        migrations.AddField(
            model_name='absensimagang',
            name='dokumen_persetujuan',
            field=models.FileField(blank=True, help_text='Dokumen persetujuan atasan untuk WFA (.png, .jpg, .pdf, max 5MB)', null=True, upload_to='absensi/wfa_approval/%Y/%m/%d/', validators=[apps.absensi.validators.validate_file_size_wfa, apps.absensi.validators.validate_wfa_document_extension]),
        ),
        migrations.AddField(
            model_name='absensimagang',
            name='hr_keterangan',
            field=models.TextField(blank=True, help_text='Keterangan bebas dari HR untuk karyawan yang tidak hadir atau tidak ada aktivitas', null=True),
        ),
        migrations.DeleteModel(
            name='FaceData',
        ),
        migrations.DeleteModel(
            name='FaceEncoding',
        ),
    ]
