# Generated by Django 3.2.6 on 2026-04-08 08:51

from datetime import time

from django.db import migrations, models


def forwards_set_reminder_1015(apps, schema_editor):
    Rules = apps.get_model('absensi', 'Rules')
    Rules.objects.update(batas_checkin_reminder=time(10, 15))


def backwards_set_reminder_1000(apps, schema_editor):
    Rules = apps.get_model('absensi', 'Rules')
    Rules.objects.update(batas_checkin_reminder=time(10, 0))


class Migration(migrations.Migration):

    dependencies = [
        ('absensi', '0024_add_rules_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rules',
            name='batas_checkin_reminder',
            field=models.TimeField(default='10:15:00', help_text='Setelah jam ini check-in wajib Izin Telat (default: 10:15)'),
        ),
        migrations.RunPython(forwards_set_reminder_1015, backwards_set_reminder_1000),
    ]
