# Generated by Django 3.2.6 on 2026-04-08 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absensi', '0025_checkin_reminder_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='absensimagang',
            name='checkout_reminder_sent',
            field=models.BooleanField(default=False, help_text='Flag Web Push reminder absen pulang (setelah durasi kerja minimal tercapai)'),
        ),
    ]
