# Generated by Django 3.2.6 on 2025-12-31 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hrd', '0031_auto_20251224_1329'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('overtime_alert', 'Alert Lembur 10 Jam'), ('reminder', 'Reminder'), ('approval', 'Approval Status'), ('general', 'General Notification')], default='general', max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('fonnte_response', models.JSONField(blank=True, help_text='Raw response dari Fonnte API', null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('karyawan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_logs', to='hrd.karyawan')),
            ],
            options={
                'verbose_name': 'WhatsApp Log',
                'verbose_name_plural': 'WhatsApp Logs',
                'db_table': 'whatsapp_log',
                'ordering': ['-sent_at'],
            },
        ),
    ]
