# Generated by Django 3.2.6 on 2026-04-08 09:10

from datetime import time

from django.db import migrations, models


def create_checkout_schedule(apps, schema_editor):
    ReminderSchedule = apps.get_model('notifikasi', 'ReminderSchedule')
    ReminderSchedule.objects.get_or_create(
        schedule_type='checkout_reminder',
        defaults={
            'run_time': time(0, 0),
            'is_active': False,
        },
    )


def remove_checkout_schedule(apps, schema_editor):
    ReminderSchedule = apps.get_model('notifikasi', 'ReminderSchedule')
    ReminderSchedule.objects.filter(schedule_type='checkout_reminder').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('notifikasi', '0004_remove_reminderschedule_message_template'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reminderschedule',
            options={'ordering': ['schedule_type'], 'verbose_name': 'Reminder Schedule', 'verbose_name_plural': 'Reminder Schedules'},
        ),
        migrations.AlterField(
            model_name='reminderschedule',
            name='schedule_type',
            field=models.CharField(choices=[('checkin_reminder', 'Reminder Absen Masuk'), ('overtime_alert', 'Reminder Klaim Lembur'), ('checkout_reminder', 'Reminder Absen Pulang (durasi kerja)')], help_text='Maksimal satu jadwal aktif per tipe', max_length=20, unique=True),
        ),
        migrations.RunPython(create_checkout_schedule, remove_checkout_schedule),
    ]
