# Generated by Django 3.2.6 on 2026-04-08 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifikasi', '0005_checkout_reminder_webpush'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminderschedule',
            name='schedule_type',
            field=models.CharField(choices=[('checkin_reminder', 'Reminder Absen Masuk'), ('overtime_alert', 'Reminder Klaim Lembur'), ('checkout_reminder', 'Reminder Absen Pulang')], help_text='Maksimal satu jadwal aktif per tipe', max_length=20, unique=True),
        ),
    ]
