# Generated by Django 3.2.6 on 2025-06-18 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('HRD', 'HRD'), ('Karyawan Tetap', 'Karyawan Tetap'), ('Magang', 'Magang'), ('Part Time', 'Part Time'), ('Freelance', 'Freelance'), ('Project', 'Project')], max_length=20),
        ),
    ]
