# Generated by Django 3.2.6 on 2025-12-24 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('HRD', 'HRD'), ('Karyawan Tetap', 'Fulltime'), ('Magang', 'Magang'), ('Part Time', 'Part Time'), ('Freelance', 'Freelance'), ('Project', 'Project')], max_length=20),
        ),
    ]
