# Generated by Django 3.2.6 on 2025-06-07 12:52

import apps.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrd', '0020_alter_karyawan_divisi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuti',
            name='file_dokumen_formal',
            field=models.FileField(blank=True, help_text='File .docx cuti yang ditandatangani', null=True, upload_to='cuti/file_dokumen_formal/', validators=[apps.utils.validators.validate_file_size, apps.utils.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='cuti',
            name='file_pengajuan',
            field=models.FileField(blank=True, null=True, upload_to='cuti/file_pengajuan/', validators=[apps.utils.validators.validate_file_size, apps.utils.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='cuti',
            name='file_persetujuan',
            field=models.FileField(blank=True, null=True, upload_to='cuti/file_persetujuan/', validators=[apps.utils.validators.validate_file_size, apps.utils.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='izin',
            name='file_pengajuan',
            field=models.FileField(blank=True, null=True, upload_to='izin/file_pengajuan/', validators=[apps.utils.validators.validate_file_size, apps.utils.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='izin',
            name='file_persetujuan',
            field=models.FileField(blank=True, null=True, upload_to='izin/file_persetujuan/', validators=[apps.utils.validators.validate_file_size, apps.utils.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='tidakambilcuti',
            name='file_pengajuan',
            field=models.FileField(blank=True, null=True, upload_to='tidak_ambil_cuti/file_pengajuan/', validators=[apps.utils.validators.validate_file_size, apps.utils.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='tidakambilcuti',
            name='file_persetujuan',
            field=models.FileField(blank=True, null=True, upload_to='tidak_ambil_cuti/file_persetujuan/', validators=[apps.utils.validators.validate_file_size, apps.utils.validators.validate_file_extension]),
        ),
    ]
