# Generated by Django 3.2.6 on 2025-06-18 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrd', '0021_auto_20250607_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='karyawan',
            name='kabupaten_kota',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='karyawan',
            name='provinsi',
            field=models.CharField(blank=True, choices=[('11', 'ACEH'), ('12', 'SUMATERA UTARA'), ('13', 'SUMATERA BARAT'), ('14', 'RIAU'), ('15', 'JAMBI'), ('16', 'SUMATERA SELATAN'), ('17', 'BENGKULU'), ('18', 'LAMPUNG'), ('19', 'KEPULAUAN BANGKA BELITUNG'), ('21', 'KEPULAUAN RIAU'), ('31', 'DKI JAKARTA'), ('32', 'JAWA BARAT'), ('33', 'JAWA TENGAH'), ('34', 'DI YOGYAKARTA'), ('35', 'JAWA TIMUR'), ('36', 'BANTEN'), ('51', 'BALI'), ('52', 'NUSA TENGGARA BARAT'), ('53', 'NUSA TENGGARA TIMUR'), ('61', 'KALIMANTAN BARAT'), ('62', 'KALIMANTAN TENGAH'), ('63', 'KALIMANTAN SELATAN'), ('64', 'KALIMANTAN TIMUR'), ('65', 'KALIMANTAN UTARA'), ('71', 'SULAWESI UTARA'), ('72', 'SULAWESI TENGAH'), ('73', 'SULAWESI SELATAN'), ('74', 'SULAWESI TENGGARA'), ('75', 'GORONTALO'), ('76', 'SULAWESI BARAT'), ('81', 'MALUKU'), ('82', 'MALUKU UTARA'), ('91', 'PAPUA BARAT'), ('92', 'PAPUA BARAT DAYA'), ('94', 'PAPUA'), ('95', 'PAPUA SELATAN'), ('96', 'PAPUA TENGAH'), ('97', 'PAPUA PEGUNUNGAN')], max_length=2, null=True),
        ),
    ]
