# Generated by Django 3.2.6 on 2025-06-28 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrd', '0022_auto_20250618_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailjatahcuti',
            name='tanggal_terpakai',
            field=models.DateField(blank=True, null=True),
        ),
    ]
