# Generated by Django 3.2.6 on 2025-08-27 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrd', '0023_detailjatahcuti_tanggal_terpakai'),
    ]

    operations = [
        migrations.AddField(
            model_name='tidakambilcuti',
            name='is_processed',
            field=models.BooleanField(default=False, help_text='Apakah sudah diproses untuk adjustment jatah cuti'),
        ),
        migrations.AddField(
            model_name='tidakambilcuti',
            name='scenario',
            field=models.CharField(blank=True, choices=[('claim_back', 'Claim Kembali - Cuti sudah terpotong'), ('prevent_cut', 'Pencegahan Pemotongan - Cuti belum terpotong')], help_text='jenis scenario tidak ambil cuti', max_length=20, null=True),
        ),
    ]
