# Generated by Django 3.2.6 on 2025-08-27 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrd', '0024_auto_20250827_0747'),
    ]

    operations = [
        migrations.AddField(
            model_name='tidakambilcuti',
            name='jenis_pengajuan',
            field=models.CharField(default='tidak_ambil_cuti', help_text='Jenis pengajuan, default: tidak_ambil_cuti', max_length=30),
        ),
    ]
