# Generated by Django 3.2.6 on 2025-09-08 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hrd', '0025_tidakambilcuti_jenis_pengajuan'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuangRapat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, unique=True)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('kapasitas', models.IntegerField(default=10)),
                ('fasilitas', models.TextField(blank=True, help_text='Contoh: Proyektor, AC, Whiteboard', null=True)),
                ('warna_kalender', models.CharField(default='#007bff', help_text='Hex color untuk kalender', max_length=7)),
                ('aktif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ruang Rapat',
                'verbose_name_plural': 'Ruang Rapat',
                'db_table': 'ruang_rapat',
            },
        ),
        migrations.CreateModel(
            name='BookingRuangRapat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('tanggal', models.DateField()),
                ('waktu_mulai', models.TimeField()),
                ('waktu_selesai', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ruang_rapat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='hrd.ruangrapat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_ruang_rapat', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Booking Ruang Rapat',
                'verbose_name_plural': 'Booking Ruang Rapat',
                'db_table': 'booking_ruang_rapat',
                'ordering': ['tanggal', 'waktu_mulai'],
            },
        ),
        migrations.AddConstraint(
            model_name='bookingruangrapat',
            constraint=models.CheckConstraint(check=models.Q(('waktu_selesai__gt', django.db.models.expressions.F('waktu_mulai'))), name='waktu_selesai_after_waktu_mulai'),
        ),
    ]
