# Generated by Django 3.2.6 on 2025-09-18 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrd', '0026_auto_20250909_0111'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailjatahcuti',
            name='tersedia',
            field=models.BooleanField(default=True, help_text='False jika bulan ini sebelum karyawan masuk kerja'),
        ),
    ]
