# Generated by Django 3.2.6 on 2025-12-03 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrd', '0029_alter_karyawan_divisi'),
    ]

    operations = [
        migrations.AddField(
            model_name='izin',
            name='kompensasi_lembur',
            field=models.CharField(blank=True, choices=[('makan', 'Uang Makan (Max 35rb)'), ('masuk_siang', 'Masuk siang untuk esok hari')], help_text='Masuk Siang (Esok Hari)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='izin',
            name='jenis_izin',
            field=models.CharField(choices=[('telat', 'Izin Telat'), ('wfh', 'Izin WFH'), ('klaim_lembur', 'Klaim Lembur')], max_length=50),
        ),
    ]
