# Generated by Django 3.2.6 on 2025-12-24 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrd', '0030_auto_20251203_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='izin',
            name='jenis_izin',
            field=models.CharField(choices=[('telat', 'Izin Telat'), ('wfh', 'Izin WFH'), ('klaim_lembur', 'Izin Lembur'), ('business_trip', 'Izin Business Trip')], max_length=50),
        ),
        migrations.AlterField(
            model_name='izin',
            name='kompensasi_lembur',
            field=models.CharField(blank=True, choices=[('makan', 'Uang Makan (Max 35rb)'), ('masuk_siang', 'Masuk Siang (Esok Hari)')], help_text='Kompensasi untuk pengajuan Izin Lembur', max_length=20, null=True),
        ),
    ]
