# Generated by Django 3.2.6 on 2025-12-31 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrd', '0031_auto_20251224_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='cutibersama',
            name='jenis',
            field=models.CharField(choices=[('Cuti Bersama', 'Cuti Bersama'), ('WFH', 'WFH'), ('WFA', 'WFA')], default='Cuti Bersama', max_length=20),
        ),
    ]
