# Generated by Django 3.2.6 on 2026-01-08 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrd', '0032_cutibersama_jenis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cutibersama',
            name='jenis',
            field=models.CharField(choices=[('Cuti Bersama', 'Cuti Bersama'), ('WFH', 'WFH')], default='Cuti Bersama', max_length=20),
        ),
    ]
