# Generated by Django 3.2.6 on 2026-01-29 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrd', '0034_update_izin_choices_and_overtime_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cutibersama',
            name='jenis',
            field=models.CharField(choices=[('Cuti Bersama', 'Cuti Bersama'), ('WFA', 'WFA'), ('WFH', 'WFH')], default='Cuti Bersama', max_length=20),
        ),
        migrations.AlterField(
            model_name='izin',
            name='jenis_izin',
            field=models.CharField(choices=[('telat', 'Izin Telat'), ('sakit', 'Izin Sakit'), ('pulang_awal', 'Izin Pulang Awal'), ('wfa', 'Izin WFA'), ('wfh', 'Izin WFH'), ('klaim_lembur', 'Izin Lembur'), ('business_trip', 'Izin Business Trip')], max_length=50),
        ),
    ]
